### ISSUE TITLE
A new checkbox will need to be added to the Design Information tab for AquaPrime. 

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaPrime2.0#1]

**Comment by chukon** [comment]
![1](https://user-images.githubusercontent.com/3256516/28973623-6bf375ac-78f9-11e7-89a3-8b7d1acaf85c.png)

**Comment by chukon** [comment]
Ready to test in APD Dev

**Comment by asunday3** [comment]
APD crashes after selecting AquaPrime checkbox.  Also, currently does not allow you to have tabs for both AquaPrime and tertiary filter.
