### ISSUE TITLE
Report: O & M 

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaPrime2.0#13]
Keep same format as tertiary.
Need to be able to manually enter power consumption
Updated background table will be provided. 
![13](https://user-images.githubusercontent.com/3256516/28974263-603c6f6e-78fb-11e7-9855-0d7d6d397961.png)

**Comment by chukon** [comment]
Do you have the calcs need for this report?

**Comment by mhughes1** [comment]
Please see the attached worksheet with the new rows highlighted.
[Copy of tbl000FilterOMMaintenance.xlsx](https://github.com/aquaaerobic/AquaPrime2.0/files/1549282/Copy.of.tbl000FilterOMMaintenance.xlsx)

**Comment by chukon** [comment]
Ready to test AquaPrime O&M

**Comment by mhughes1** [comment]
Where do I find this report on the reports screen?  

![image](https://user-images.githubusercontent.com/34448244/33892448-5bd0d954-df1e-11e7-90ea-9818427c13ee.png)

**Comment by chukon** [comment]
Click on O&M under sceren shots

**Comment by mhughes1** [comment]
This one is pulling in the tertiary O&M.  There are cases where we would need separate O&M reports for AquaPrime filters and cloth media filters. 

I'm looking at design #150325, which has both AquaPrime and regular cloth media filters.

![image](https://user-images.githubusercontent.com/34448244/33942985-4b8d4b58-dfdd-11e7-96db-4375176c768d.png)

**Comment by chukon** [comment]
Got it. I put a new checkbox for O&M for Prime. Restart APD Dev and try again

**Comment by mhughes1** [comment]
The new button works.  

The power consumption numbers for the AquaPrime O&M report need to be manual entry in the O&M tab. 

![image](https://user-images.githubusercontent.com/34448244/33947280-98f6ed98-dfe9-11e7-83f0-a76ad2352ed0.png)

![image](https://user-images.githubusercontent.com/34448244/33947304-a7e5304e-dfe9-11e7-973e-0579e037ef2a.png)

**Comment by chukon** [comment]
1) 2) and 3) Numbers?

**Comment by mhughes1** [comment]
We need to be able to enter in numbers for fields 1., 2., and 3.  The total should be calculated as the sum of 1, 2, and 3.

**Comment by chukon** [comment]
Ok, This is complete.  Restart APD Dev and test.

**Comment by mhughes1** [comment]
Looks good.  

It looks like we need a couple more digits available.  We need to be able to use up to six digits (1,000,000) and do not need any decimals.  I'm currently getting ### when I enter values over four digits. 

![image](https://user-images.githubusercontent.com/34448244/33950035-e706ec8e-dff0-11e7-9470-c7aa41ae333e.png)

![image](https://user-images.githubusercontent.com/34448244/33950065-ff370776-dff0-11e7-80f4-55452c6a78a3.png)

**Comment by chukon** [comment]
Fixed, Run Report Again in APD Dev
