### ISSUE TITLE
Need Updated AquaPrime Calcs for Metal Salts, Polymer, and Loading Calcs

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaPrime2.0#19]
Mark, please See attached calculations I copied from Tertiary Filter for AquaPrime and update calculations. The calculated output values for tabs Metal Salts, Polymers and Loading Calcs are determined by the Influent and Effluent input.  Since the Influent and Effluent inputs are different, AquaPrime calcs do not have Inlet Total Phosphorous and Anticipated Effluent Total Phosphorous. In addition the calculations for the loading calcs tabs needs updated as well. 

Thanks, 
Chuck
[AquaPrimeCalcs.docx](https://github.com/aquaaerobic/AquaPrime2.0/files/1330185/AquaPrimeCalcs.docx)

**Comment by chukon** [comment]
[Metal Salt Calcs.zip](https://github.com/aquaaerobic/AquaPrime2.0/files/1330194/Metal.Salt.Calcs.zip)

**Comment by asunday3** [comment]
chuck,

Noticed the following:
- There is still a check box for Aquaprime under "filter (SBR Required).  I assume this will be deleted since new check box for AquaPrime will be added.
- I don't see where to add in ADF MDF and PDF values.  should be inputs in "Influent" tab I believe per Mark's instruction.  Other tabs are marked as "in development".

**Comment by chukon** [comment]
No, the green AquaPrime will stay because there are hundreds of designs that used that checkbox which was just for placeholder sake.

**Comment by asunday3** [comment]
Following are comments:
-        I cannot press enter to move to the next input box.
-        The cloth type should be PF-14 by default on the Loading Calcs tab.
-        We need a drop down on the Loading Calcs tab to select the application type.  This application type will affect the design solids loading values.  Options should be "Primary", "Primary Effluent", and "Wet Weather".  I don't think this was indicated in the worksheet Mark gave to you.
-        The Design Solids Loads field was a header on Mark's worksheet and does not need a value associated with it.
- Only options for "Filter Type" should be "AquaPrime Package" and "AquaPrime Concrete".
- Need to keep "Prior Treatment" input as we have for tertiary filters.
- CBOD checkbox is not needed.  "CBOD" should be another option on influent and effluent tabs in addition to "BOD" and "COD"
