### ISSUE TITLE
AquaPrime Prelim Report

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaPrime2.0#24]
AquaPrime Design Summary has been created and added to Preliminary Proposal  Report.

Please test in APD Development.

Chuck
[1282017_83_29_150056_PreliminaryProposal.pdf](https://github.com/aquaaerobic/AquaPrime2.0/files/1547704/1282017_83_29_150056_PreliminaryProposal.pdf)

**Comment by chukon** [comment]
[Prelim Report for AquaPrime  .zip](https://github.com/aquaaerobic/AquaPrime2.0/files/1547801/Prelim.Report.for.AquaPrime.zip)

**Comment by mhughes1** [comment]
I'm closing this issue.  Please see other specific calculation issue.
