### ISSUE TITLE
AquaPrime 2.0 Confirm Calculations are correct.

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaPrime2.0#25]
![2017-12-11_0617](https://user-images.githubusercontent.com/3256516/33830822-5af5ca46-de3b-11e7-8976-56b0e367e265.png)

**Comment by mhughes1** [comment]
The #Disks Required for Solids Loading is Incorrect.  (Design #150295)
![image](https://user-images.githubusercontent.com/34448244/33841321-07025c02-de5d-11e7-8329-ec26836db6cf.png)

The correct value in this case would be 9.70, which is showing up correctly in the Controlling Total Number of Disks field.

**Comment by chukon** [comment]
Mark, ready to test.

**Comment by mhughes1** [comment]
works for me.
