### ISSUE TITLE
Flow and Solids Loading Conditions incorrect on design report

### ISSUE THREAD

**Issue by mhughes1** [aquaaerobic/AquaPrime2.0#26]
The flow conditions and solids load conditions shown on the design report are the values entered in the table at the bottom of the AquaPrime calcs tab.  These values should be calculated for the specific design.   The calculations are shown on the bottom of the AquaPrime calcs sheet on the example Excel spreadsheet. 

![image](https://user-images.githubusercontent.com/34448244/33836926-79d3776e-de50-11e7-9d24-ac5867cfe487.png)

![image](https://user-images.githubusercontent.com/34448244/33836943-864a731c-de50-11e7-9476-6cbb2f8434a7.png)

**Comment by chukon** [comment]
Mark, ready to test report changes

**Comment by mhughes1** [comment]
Just a few minor text edits. 
![image](https://user-images.githubusercontent.com/34448244/33851710-70612c12-de7d-11e7-867a-a3c42bcff55c.png)

**Comment by chukon** [comment]
Mark, ready to test
