### ISSUE TITLE
Max Design Flow on Report Referencing Incorrect Field

### ISSUE THREAD

**Issue by mhughes1** [aquaaerobic/AquaPrime2.0#27]
The Max Design Flow in Design #150302 is 2 MGD, but is showing up as 3 MGD on the design report.  

![image](https://user-images.githubusercontent.com/34448244/33851486-c1be7106-de7c-11e7-9f43-c0a6ed056d33.png)

**Comment by chukon** [comment]
This is ready to test

**Comment by mhughes1** [comment]
works for me.
