### ISSUE TITLE
Filter Supervision and Freight Tab does not disappear

### ISSUE THREAD

**Issue by mhughes1** [aquaaerobic/AquaPrime2.0#28]
For tertiary filters, the freight and startup tab disappears when someone clicks on any of the first five tabs in the cloth media filter section.  This does not happen in the AquaPrime section.  

![image](https://user-images.githubusercontent.com/34448244/33892014-49dd706e-df1d-11e7-8e5d-67bb0390c40c.png)

**Comment by chukon** [comment]
Fixed. Restart APD Dev and Test.
