### ISSUE TITLE
AquaPrime Cost Report Will not open

### ISSUE THREAD

**Issue by mhughes1** [aquaaerobic/AquaPrime2.0#29]
I'm working in Design #150325 and the AquaPrime cost report will not open. 

![image](https://user-images.githubusercontent.com/34448244/33892248-ee1ecf10-df1d-11e7-9859-7058b91a233c.png)

**Comment by chukon** [comment]
Mark, 
Fixed, ready to test.

**Comment by mhughes1** [comment]
Works for me!
